function F = dynamicsFun(in1)
%DYNAMICSFUN
%    F = DYNAMICSFUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    23-Mar-2016 11:08:24

alat = in1(6,:);
alon = in1(4,:);
phi = in1(9,:);
vlat = in1(5,:);
vlon = in1(3,:);
x = in1(1,:);
y = in1(2,:);
yaw = in1(7,:);
yawRate = in1(8,:);
t2 = cos(yaw);
t3 = sin(yaw);
t4 = 1.0./vlon;
F = [x-t2.*vlat.*(1.0./4.0e1)-t3.*vlon.*(1.0./4.0e1);y-t3.*vlat.*(1.0./4.0e1)+t2.*vlon.*(1.0./4.0e1);alon.*(1.0./4.0e1)+vlon;alon;alat.*(1.0./4.0e1)+vlat;alat+phi.*1.517394034230414+yawRate.*(t4.*1.742794142276993e1-vlon).*(1.0./4.0e1)-t4.*vlat.*2.784441782945676;yaw+yawRate.*(1.0./4.0e1);phi.*8.725414554685308e-1+yawRate+t4.*vlat.*2.269366943836399e-1-t4.*yawRate.*2.795016364490974;phi];
