export default {
    ego: require('./ego.png'),
    vehicle: require('./vehicle.png'),
    transport: require('./transport2.png'),
    otherTransport: require('./otherTransport.png'),
    line: require('./line.png'),
    road: require('./road.png'),
    miniEgo: require('./miniEgo.png'),
    miniOther: require('./miniOther.png'),
    miniRoad: require('./miniRoad.png'),
    indicator: require('./indicator.png'),
    blinker: require('./blinker.png'),
    brake: require('./brake.png'),
    zoomIn: require('./zoom-in.png'),
    zoomOut: require('./zoom-out.png'),
    construction: require('./icon-construction.png'),
    intersectionRight: require('./icon-intersection-right.png'),
    intersectionLeft: require('./icon-intersection-left.png'),
    emergency: require('./icon-emergency.png')
}
